### ISSUE TITLE
Implement a vaadin data provider

### ISSUE THREAD

**Issue by ado2000** [alejandro-du/report-ui#1]
Hi, what about to implement a vaadin data provider ?

In this case can be very useful to pass the data in the vaadin way.

**Comment by alejandro-du** [comment]
Sorry for the late replay. The feature is now available in version 3.0.0 which requires Vaadin 14.0.2 or later. Example of usage:
```java
report.setDataProvider(dataProvider);
```
Please note that the `setDataProvider(DataProvider)` method is simply a shortcut for:
```java
setItems(dataProvider.fetch(new Query<>()).collect(Collectors.toList()));
```
