### ISSUE TITLE
replicate JRViewer

### ISSUE THREAD

**Issue by voa-rvirayii** [alejandro-du/report-ui#3]
![vaad](https://user-images.githubusercontent.com/53815829/63799466-c31b1c80-c93e-11e9-9d33-70a2a53d6ac3.JPG)

After trying to explore. having difficulties in utilizing this printpreview function like zoom in and zoom out. any idea how we can do it ?

**Comment by alejandro-du** [comment]
This looks like an issue for the **JasperReports project** not the **Report UI add-on for Vaadin** (https://vaadin.com/directory/component/report-ui).
