### ISSUE TITLE
Two top level (Span, HTML) with Vaadin 23

### ISSUE THREAD

**Issue by WilliamFreau** [alejandro-du/report-ui#36]
Hi,
since we upgrade to Vaadin23 we face an issue while exporting the grid.

```
java.lang.IllegalArgumentException: HTML must contain exactly one top level element (ignoring text nodes). Found 2 elements with the tag names span, html
	at com.vaadin.flow.component.Html.setOuterHtml(Html.java:128)
	at com.vaadin.flow.component.Html.<init>(Html.java:113)
	at org.vaadin.reports.PrintPreviewReport.setItems(PrintPreviewReport.java:126)
	at org.vaadin.reports.PrintPreviewReport.getStreamResource(PrintPreviewReport.java:149)
	at org.vaadin.reports.PrintPreviewReport.getStreamResource(PrintPreviewReport.java:144)
```

It's seems to be on line 126 when you create a Vaadin HTML element. The parser behind the HTML element create more than one HTML tag.

I'm not sure if it's your addon or the Vaadin HTML component that has change. But now the export fail each time.

Can I have your please.
Best regards

**Comment by WilliamFreau** [comment]
I've replace the line 126 by:
```java
Html htmlContent = new Html(Jsoup.parse(outputStream.toString(StandardCharsets.UTF_8.name())).body().html());
```
I'm not sure if it's working for all cases but now the export work again.

**Comment by McPringle** [comment]
Thanks, @WilliamFreau for figuring this out. Maybe you can create a PR that might be merged by @alejandro-du?

**Comment by llizmk** [comment]
Hello may i ask exxactly how u fixed your problem , my code is like this and i get the same error : 
```
@Route(value = "/Rapport" , layout = MainLayout.class)
@PageTitle("Rapport")
public class Rapport extends VerticalLayout {
    private VenteService venteService;
    public Rapport(VenteService venteService) {
        this.venteService = venteService;
        PrintPreviewReport<Vente> rapport = new PrintPreviewReport<>(Vente.class);
        rapport.setItems(venteService.getFilteredVentesAll("All"));
        add(rapport);
    }
}
```

**Comment by alejandro-du** [comment]
Please feel free to reopen and provide additional information if you are still facing this issue.
