### ISSUE TITLE
Charts are not shown when navigating with org.springframework.boot.loader.WarLauncher

### ISSUE THREAD

**Issue by Albert-Ham** [alejandro-du/report-ui#8]
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by alejandro-du** [comment]
Can you elaborate a bit more, please? If you can provide a minimal project that reproduces the issue, that would help a lot.
